// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: price_contract.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace AElf.Contracts.Price {

  #region Events
  public partial class NewestSwapPriceUpdated : aelf::IEvent<NewestSwapPriceUpdated>
  {
    public global::System.Collections.Generic.IEnumerable<NewestSwapPriceUpdated> GetIndexed()
    {
      return new List<NewestSwapPriceUpdated>
      {
      };
    }

    public NewestSwapPriceUpdated GetNonIndexed()
    {
      return new NewestSwapPriceUpdated
      {
        TokenSymbol = TokenSymbol,
        TargetTokenSymbol = TargetTokenSymbol,
        Price = Price,
        Timestamp = Timestamp,
        QueryId = QueryId,
        UnderlyingTokenPrice = UnderlyingTokenPrice,
      };
    }
  }

  public partial class NewestExchangePriceUpdated : aelf::IEvent<NewestExchangePriceUpdated>
  {
    public global::System.Collections.Generic.IEnumerable<NewestExchangePriceUpdated> GetIndexed()
    {
      return new List<NewestExchangePriceUpdated>
      {
      };
    }

    public NewestExchangePriceUpdated GetNonIndexed()
    {
      return new NewestExchangePriceUpdated
      {
        TokenSymbol = TokenSymbol,
        TargetTokenSymbol = TargetTokenSymbol,
        Price = Price,
        Timestamp = Timestamp,
        PriceSupplier = PriceSupplier,
        QueryId = QueryId,
      };
    }
  }

  #endregion
}
#endregion

